import React from 'react'
import Head from 'next/head'
import { Layout, Space } from 'antd';
const { Header, Footer, Sider, Content } = Layout;


export default function MainLayout({ children }) {
    return (
        <Layout style={{ minHeight: '100vh' }}>
            <Head>
                <title>AI Image Generator</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Content style={{padding:'16px 24px'}}>{children}</Content>
            <Footer style={{textAlign:'center'}}>Copyright @{new Date().getFullYear()}. All right reserved.</Footer>
        </Layout>
    )
}
